### ISSUE TITLE
story - ca un vizitator al platformei as vrea sa pot naviga dupa urmatoarele rute

### ISSUE THREAD

**Issue by razvanpavel** [code4romania/monitorizare-vot-votanti-client#1]
```
/acasa
/sesizari
/statistici
/reguli-vot
/despre-noi
```

**Comment by ccioloca** [comment]
acasa si sesizari din ce am vazut este o singura ruta. Daca se doreste impartirea ei in 2, se rezolva.

**Comment by razvanpavel** [comment]
Doua te rog. Prezentam toate sesizarile la ruta respectiva, pe home doar primele x.
