### ISSUE TITLE
Incident description word-break overflow

### ISSUE THREAD

**Issue by x-spert** [code4romania/monitorizare-vot-votanti-client#12]
# Fix overflow de tip word in descrierea unei sesizari

Creare clasa `.incident-description` cu proprietatea `word-break: break-word;` si adaugare la container-ul specific.

## Issue Type

- [x] Bug 
- [ ] Feature 

## Description

Textul din container-ul ce contine descrierea sesizarii face overflow.
![incident-description-overflow](https://cloud.githubusercontent.com/assets/16935452/21108031/4d64f1bc-c09c-11e6-8554-65c5b4fda6fd.png)

## Steps to reproduce

Browser: Mozilla Firefox 52.0a2 (2016-12-12) (32-bit) si Chrome Version 55.0.2883.87 m

**Comment by razvanpavel** [comment]
@x-spert ai timp sa le faci si un equal heights din flexbox? era pe todo list dar n-am mai ajuns. Merci!

**Comment by x-spert** [comment]
O sa incerc. :)
