### ISSUE TITLE
Change message icon

### ISSUE THREAD

**Issue by overeha** [code4romania/monitorizare-vot-votanti-client#45]
Currently all incoming messages from citizens are displayed in a box that has an icon featuring number 11 on it. This number is actually the date of the last parliamentary elections. This icon should be dynamic and display the date the message has been posted.

**Comment by danichim** [comment]
https://github.com/code4romania/monitorizare-vot-votanti-client/issues/45

**Comment by aniri** [comment]
this issue has two fixes from hackday 1:
https://github.com/code4romania/monitorizare-vot-votanti-client/pull/49
https://github.com/code4romania/monitorizare-vot-votanti-client/pull/48

please reuse code from them and improve the look of the message icon. it should be similar to the one from left below and use the font from the site:

![options](https://user-images.githubusercontent.com/1358055/53284617-77a16f00-375f-11e9-89ba-62ea889ef0d6.png)

**Comment by RaduCStefanescu** [comment]
In progress @danichim

**Comment by danichim** [comment]
https://github.com/code4romania/monitorizare-vot-votanti-client/pull/48 PR DONE
