### ISSUE TITLE
Login into new-admin

### ISSUE THREAD

**Issue by razvanpavel** [code4romania/monitorizare-vot-votanti-client#56]
Merging front end of Monitorizare Vot Admin to Monitorizare Vot Client.
A simple login page should be made available on the monitorizare vot website.
Login should redirect to "/messages" when login is successful - please check bellow how the menu should look like when Admin logs in.

The menu should change in case an Admin logs in the platform.
The menu for Admin should have the following listings: MESSAGES, PAGES, FORMS
Please checkout this UX for more details about how the menu should look like for Admin:
https://www.figma.com/proto/DD5l64FEG0VYIcsGzPrN0CzJ/MV---platforma-publica---admin?redirected=1&scaling=min-zoom&node-id=5%3A70

**Comment by dmfarcas** [comment]
https://github.com/code4romania/monitorizare-vot-votanti-client/pull/59

**Comment by RaduCStefanescu** [comment]
Also related to this issue: #58

**Comment by RaduCStefanescu** [comment]
This one has been implemented in #77
