### ISSUE TITLE
Create a new MESSAGES menu item

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/monitorizare-vot-votanti-client#61]
A new MESSAGES menu item should be available in the public platform website.
The menu item should be available **only for ADMIN user**. The menu item **should not be displayed for a regular user**

Please check the UX for look and feel of the new menu item:
https://www.figma.com/proto/DD5l64FEG0VYIcsGzPrN0CzJ/MV---platforma-publica---admin?redirected=1&scaling=min-zoom&node-id=5%3A70

**Comment by andrei1489** [comment]
I will take this

**Comment by RaduCStefanescu** [comment]
In progress @andrei1489

**Comment by RaduCStefanescu** [comment]
We can close this issue, it is implemented in #79 and #80
