### ISSUE TITLE
Display all incidents in the MESSAGES panel

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/monitorizare-vot-votanti-client#62]
The MESSAGES panel should display all the incidents in the database. 
This is related to #61 
The backend already exposes an endpoint for retrieving all messages GET /v1/incidents

Please check the UX for additional details about look and feel:

https://www.figma.com/proto/DD5l64FEG0VYIcsGzPrN0CzJ/MV---platforma-publica---admin?redirected=1&scaling=min-zoom&node-id=1%3A182

**Comment by andrei1489** [comment]
I will take this.

**Comment by RaduCStefanescu** [comment]
In progress @andrei1489

**Comment by RaduCStefanescu** [comment]
We can close this issue, it is implemented in #79 and #80
