### ISSUE TITLE
Accept/Reject incidents in the MESSAGES panel

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/monitorizare-vot-votanti-client#63]
When selecting an incident in the messages panel, the admin user should be able to mark the incident as approved/rejected.

The backend already accepts these actions, the endpoints are exposed with 
POST incidents/{incidentId}/approve and POST incidents/{incidentId}/reject

Only admin user should be able to issue these operations.

Please check the UX for more detailed information:
https://www.figma.com/proto/DD5l64FEG0VYIcsGzPrN0CzJ/MV---platforma-publica---admin?redirected=1&scaling=min-zoom&node-id=3%3A59

**Comment by andrei1489** [comment]
I will take this

**Comment by RaduCStefanescu** [comment]
In progress @andrei1489

**Comment by RaduCStefanescu** [comment]
We can close this issue, it is implemented in #79 and #80
