### ISSUE TITLE
Add upload image feature when user adds incident on public platform

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/monitorizare-vot-votanti-client#65]
Currently the user cannot add an image when posting about an incident (please checkout the image below)
The incident form should have an upload image section where an user can upload an image. The image is not mandatory for the submission of the form.

![image](https://user-images.githubusercontent.com/15039873/56138185-0a5fcc80-5f9f-11e9-9a34-5476678cb8c7.png)

Please check related backend issue:
https://github.com/code4romania/monitorizare-vot-votanti-api/issues/26

Below the row with "Sectia" and "Tipul sesizarii" and right above the row with captcha and "Adauga sesizare" button, we should have an entry similar to the one in the image below where a user can choose an image and upload it as part of the incident report: 

![image](https://user-images.githubusercontent.com/15039873/57308449-0da62e00-70ef-11e9-8e7c-f9e78b1d0804.png)

**Comment by horodnicdragos** [comment]
I'll grab this one.

**Comment by RaduCStefanescu** [comment]
In progress @horodnicdragos

**Comment by RaduCStefanescu** [comment]
Fixed by #91
