### ISSUE TITLE
Accept/reject buttons do not work as expected

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/monitorizare-vot-votanti-client#85]
The accept/reject buttons on the Unread/Accepted/Rejected panels do not work as expected.
No call is made to the backend to update the state of the incidents.
The backend already has implemented the accept/reject functionality.

**Comment by Andu033** [comment]
I can work on that.

**Comment by RaduCStefanescu** [comment]
Fixed by PR #94 
The bug can be closed
